#ifndef _POSL_DEFINITIONS_H_
#define _POSL_DEFINITIONS_H_

#define POSL_DATA_TJUNC 1
#define POSL_DATA_DRALL 2
#define POSL_DATA_PENT 3
#define POSL_DATA_COJACK 4

#define POSL_PARTITIONING_CLASSIC 1
#define POSL_PARTITIONING_DUAL 2
#define POSL_PARTITIONING_NODAL 3

#define POSL_INIT_ONE_READ 1
#define POSL_INIT_ALL_READ 2

#define NINTCF_SEND_INDEX 0
#define NEXTCF_SEND_INDEX 1
#define POINTSCOUNT_SEND_INDEX 2

#endif