#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "final_output_vtk.h"
#include "util_write_files.h"
#include "vol2mesh.h"

char* concat(char *s1, char *s2)
{
    size_t len1 = strlen(s1);
    size_t len2 = strlen(s2);
    char *result = malloc(len1+len2+1);
    //TODO: need to check if malloc is OK
    memcpy(result, s1, len1);
    memcpy(result+len1, s2, len2+1);
    return result;
}

void finalOutputVTK(char *file_out_prefix, int nintci, int nintcf,
	int **lcc, double *var, double *cgup, double *su) {
	int i;
	// This variables will be generated by vol2mech function
	int nodeCnt;
	int **points;
	int **elems;

	char *su_name = concat(file_out_prefix, ".SU.vtk");
	char *var_name = concat(file_out_prefix, ".VAR.vtk");
	char *cgup_name = concat(file_out_prefix, ".CGUP.vtk");

	// Generate mesh
	vol2mesh(nintci, nintcf, lcc, &nodeCnt, &points, &elems);
	// Create VTK files
	write_result_vtk(su_name, nintci, nintcf, nodeCnt,
			points, elems, su);
	write_result_vtk(var_name, nintci, nintcf, nodeCnt,
			points, elems, var);
	write_result_vtk(cgup_name, nintci, nintcf, nodeCnt,
			points, elems, cgup);

	free(su_name);
	free(var_name);
	free(cgup_name);
	for (i = 0; i < 3; i++) {// This size we got in vol2mesh
		free(points[i]);
	}
	free(points);
	for (i = 0; i < 8; i++) {
		free(elems[i]);
	}
	free(elems);
}
